routes:
  - id: wry
    uri: http://localhost:8080
    order: 1
    predicates:
      # 匹配指定日期时间之后发生的请求
      #       匹配所有：`After=`
#      - After=2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
      # 匹配指定日期时间之前发生的请求
      #       匹配所有：`Before=`
#      - Before=2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
      # 匹配指定datetime1之后和datetime2之前发生的请求，datetime1在前datetime2在后
      #       匹配所有：`Between=`
      - Between=2023-06-26T14:30:00.000+08:00[Asia/Shanghai],2023-06-26T18:30:00.000+08:00[Asia/Shanghai]
      # 匹配主机：
      #       匹配所有：`Host=`,`Host=*`
      #       单匹配：`Host=**.baidu.com`,`Host=**.alibaba.com`
      #       多匹配：`Host=**.baidu.com,**.alibaba.com`
      - Host=*
      # 匹配方法：
      #       匹配所有：`Method=`,`Path=*`
      #       单匹配：`Path=GET`,`Path=POST`
      #       多匹配：`Path=GET,POST`
      - Method=*
      # 匹配路径：
      #       匹配所有：`Path=`,`Path=/`
      #       单匹配：`Path=/a/**`,`Path=/**/*.js`
      #       多匹配：`Path=/a/**,/b/**`
      - Path=/
