routes:
  - id: wry
    uri: http://localhost:8080
    order: 1
    predicates:
      - name: Method
        args:
          pattern: GET,POST
      - name: After
        args:
          pattern: 2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
