server:
  port: 8090
routes:
  - id: wry
    uri: http://localhost:8080
    order: 1
    predicates:
      - name: Method
        args:
          pattern: GET,POST
      - name: After
        args:
          pattern: 2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
      - name: Before
        args:
          pattern: 2023-07-26T14:30:00.000+08:00[Asia/Shanghai]
      - name: Between
        args:
          pattern1: 2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
          pattern2: 2023-07-27T14:30:00.000+08:00[Asia/Shanghai]
      - name: Cookie
        args:
          pattern1: chocolate
          pattern2: 123

logger:
  level: debug