server:
  port: 8090
routes:
  - id: wry
    uri: https://chat18.aichatos.xyz/
    order: 1
    predicates:
      - Method=GET,POST
      - After=2023-06-26T14:30:00.000+08:00[Asia/Shanghai]
    filters:
      - name: AddRequestHeader
        args:
          X-Token: sss
logger:
  level: debug